import Navbar from './components/Navbar';
import Footer from './components/Footer';
import './globals.scss'
import SessionWrapper from './components/SessionWrapper';
import { Poppins } from 'next/font/google'

const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <SessionWrapper>
    <html lang="en">
      <body className={poppins.className}>
       <Navbar />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
    </SessionWrapper>
  )
}
